import { create } from 'zustand'

/**
 * Own-key conflict: detected during `ensureIdentity()` when the key
 * published on the server does not match the local key material.
 *
 * Two kinds:
 *
 * - `primary-mismatch`: the server advertises a different primary
 *   fingerprint than the one held locally. Could be server tampering
 *   (attacker replaced our key) or a brand-new key generated by a
 *   reinstall / different OpenPGP client on another device.
 *
 * - `subkey-mismatch`: same primary fingerprint in the metadata node,
 *   but the published key data (armored content of the data node) differs
 *   from the local key. Typical cause: `rotateEncryptionKey()` was run on
 *   another of our devices, adding a new encryption subkey that this
 *   device doesn't have yet.
 *
 * While a conflict is live, outbound encryption is blocked — the plugin's
 * `encrypt()` throws `own-key-conflict`. The user resolves by calling
 * either `resolveOwnKeyConflict_overwriteServer` (re-publishes local key)
 * or `resolveOwnKeyConflict_importFromServer` (restores from secret-key
 * backup, replacing local key with the server's version).
 *
 * Not persisted: conflict is re-detected on every `ensureIdentity()` call
 * (i.e. every session start). Stale persisted conflicts could block the
 * user after they already resolved it on another device.
 */
export interface OwnKeyConflict {
  kind: 'primary-mismatch' | 'subkey-mismatch'
  localFingerprint: string
  publishedFingerprint: string
  publishedDate: string
}

interface OwnKeyConflictState {
  conflict: OwnKeyConflict | null
  setConflict: (conflict: OwnKeyConflict) => void
  clearConflict: () => void
}

export const useOwnKeyConflictStore = create<OwnKeyConflictState>((set) => ({
  conflict: null,
  setConflict: (conflict) => set({ conflict }),
  clearConflict: () => set({ conflict: null }),
}))

// ---- Imperative helpers -----------------------------------------------

export function recordOwnKeyConflict(conflict: OwnKeyConflict): void {
  useOwnKeyConflictStore.getState().setConflict(conflict)
}

export function clearOwnKeyConflict(): void {
  useOwnKeyConflictStore.getState().clearConflict()
}

export function getOwnKeyConflict(): OwnKeyConflict | null {
  return useOwnKeyConflictStore.getState().conflict
}
