// Prepare the two stylesheets the converter consumes. Run immediately before
// package-build.mjs; both outputs live in the app's gitignored dist/.
//
//  1. cssEntry — the app's compiled stylesheet, copied to a stable filename.
//     Vite hashes the chunk AND derives its name from the entry, so the file
//     is variously `main-<hash>.css` or `src-<hash>.css`. Globbing the newest
//     .css in dist/assets/ is what keeps cfg.cssEntry from silently resolving
//     to nothing (the converter only warns, then ships an unstyled bundle).
//     It must stay in dist/assets/ so its `url(../fonts/…)` keeps resolving.
//
//  2. tokens — the built-in theme palettes as static CSS. At runtime `useTheme`
//     writes a theme's variables as inline styles on <html> and toggles a
//     `.light` class; there is no stylesheet for them, and a design tool has no
//     such runtime. Each palette is flattened into a selector pair here.
//     Specificity matters: index.css defines the Aurora defaults under `:root`
//     (0,1,0) and its light overrides under `.light` (0,1,0). A bare
//     `[data-theme=…]` block would tie with the latter and, coming later, would
//     beat `.light` even in light mode. Both emitted selectors are therefore
//     (0,2,0), and the dark one excludes `.light` explicitly.
//
//     Output goes under apps/fluux/ deliberately: copyTokens joins tokensGlob
//     onto <node-modules>/<tokensPkg> lexically, so a `../../` prefix would
//     escape through the node_modules/@xmpp/fluux -> apps/fluux symlink.
//
// Usage: node .design-sync/prep.mjs

import { build } from 'esbuild'
import { copyFileSync, mkdirSync, readdirSync, rmSync, statSync, writeFileSync } from 'node:fs'
import { dirname, join, resolve } from 'node:path'
import { fileURLToPath, pathToFileURL } from 'node:url'

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const ASSETS = resolve(ROOT, 'apps/fluux/dist/assets')
const CSS_OUT = join(ASSETS, 'ds-styles.css')
const TOKENS_OUT = resolve(ROOT, 'apps/fluux/dist/ds-tokens/themes.css')
const THEMES_SRC = resolve(ROOT, 'apps/fluux/src/themes/builtins/index.ts')
const TMP = resolve(ROOT, '.design-sync/.cache/themes-bundle.mjs')

// ── 1. cssEntry ──────────────────────────────────────────────────────────
let candidates
try {
  candidates = readdirSync(ASSETS).filter((f) => f.endsWith('.css') && f !== 'ds-styles.css')
} catch {
  throw new Error(`${ASSETS} does not exist — run the app build first (npm run build:sdk && npm run build:app)`)
}
if (!candidates.length) {
  throw new Error(`no compiled .css in ${ASSETS} — run the app build first`)
}
// Newest wins: a stale chunk from an earlier build can linger in dist/.
const newest = candidates
  .map((f) => ({ f, mtime: statSync(join(ASSETS, f)).mtimeMs }))
  .sort((a, b) => b.mtime - a.mtime)[0].f
copyFileSync(join(ASSETS, newest), CSS_OUT)
console.error(`ds-styles.css ← ${newest}`)

// ── 2. theme tokens ──────────────────────────────────────────────────────
mkdirSync(dirname(TMP), { recursive: true })
mkdirSync(dirname(TOKENS_OUT), { recursive: true })

await build({
  entryPoints: [THEMES_SRC],
  bundle: true,
  format: 'esm',
  platform: 'neutral',
  outfile: TMP,
  logLevel: 'warning',
})

const { builtinThemes } = await import(`${pathToFileURL(TMP).href}?t=${statSync(TMP).mtimeMs}`)
if (!Array.isArray(builtinThemes) || !builtinThemes.length) {
  throw new Error('builtins/index.ts did not export a non-empty builtinThemes array')
}

const block = (selector, vars) => {
  const entries = Object.entries(vars ?? {})
  if (!entries.length) return ''
  return `${selector} {\n${entries.map(([k, v]) => `  ${k}: ${v};`).join('\n')}\n}\n\n`
}

let css =
  '/* Generated by .design-sync/prep.mjs — do not edit by hand.\n' +
  '   Built-in Fluux theme palettes, flattened from src/themes/builtins/.\n' +
  '   Apply with data-theme="<id>" on <html>; add class="light" for light mode. */\n\n'

let emitted = 0
for (const theme of builtinThemes) {
  const sel = `:root[data-theme="${theme.id}"]`
  const body = block(`${sel}:not(.light)`, theme.variables?.dark) + block(`${sel}.light`, theme.variables?.light)
  // Aurora (id 'fluux') carries no overrides — its values are the :root
  // defaults in index.css — so it contributes no rules.
  if (!body) continue
  css += `/* ${theme.name} — ${theme.description} */\n${body}`
  emitted++
}

writeFileSync(TOKENS_OUT, css)
rmSync(TMP, { force: true })
console.error(`themes.css: ${emitted} themed palette(s) of ${builtinThemes.length} built-ins`)
